services:
  tabu-app:
    container_name: tabu-development-app
    build:
      context: .
      target: tabu-app
    ports:
      - 30000:5173
    depends_on:
      - tabu-db-api
    networks:
      - tabu-development-network

  tabu-db-api:
    build:
      context: .
      target: tabu-db-api
    container_name: tabu-development-db-api
    ports:
      - 30001:3001
    environment:
      - NODE_ENV=development
      - REDIS_HOST=tabu-redis
      - REDIS_PORT=6379
      - PORT=3001
      - API_ROUTE=/api
      - DB_SCHEMA=app_demo
    depends_on:
      - tabu-redis
    networks:
      - tabu-development-network

  tabu-redis:
    image: redis:7-alpine
    container_name: tabu-development-redis
    volumes:
      - redis-development-data:/data
    command: redis-server --appendonly yes
    networks:
      - tabu-development-network

volumes:
  redis-development-data:
    driver: local

networks:
  tabu-development-network:
    external: true
